# Form implementation generated from reading ui file 'auto_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 310, 81, 41))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);""color: black;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 150, 151, 81))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);""color: black;")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\KimoStore\\Pictures\\IMG-20240817-WA0036.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        self.required_distance = QtWidgets.QLineEdit(parent=Dialog)
        self.required_distance.setGeometry(QtCore.QRect(130, 90, 151, 41))
        self.required_distance.setStyleSheet("background-color: rgb(255, 255, 255);""color: black;")
        self.required_distance.setText("")
        self.required_distance.setObjectName("required_distance")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "distance"))
        self.required_distance.setPlaceholderText(_translate("Dialog", "enter required distance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
