# Form implementation generated from reading ui file 'Button_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Button_dialog(object):
    def setupUi(self, Button_dialog):
        Button_dialog.setObjectName("Button_dialog")
        Button_dialog.resize(495, 382)
        Button_dialog.setStyleSheet("background-color: rgb(0, 0, 34);")
        self.dial = QtWidgets.QDial(parent=Button_dialog)
        self.dial.setGeometry(QtCore.QRect(220, 150, 81, 71))
        self.dial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dial.setObjectName("dial")
        self.down_pushButton = QtWidgets.QPushButton(parent=Button_dialog)
        self.down_pushButton.setGeometry(QtCore.QRect(230, 240, 61, 121))
        self.down_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.down_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/down.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.down_pushButton.setIcon(icon)
        self.down_pushButton.setIconSize(QtCore.QSize(80, 65))
        self.down_pushButton.setCheckable(True)
        self.down_pushButton.setAutoExclusive(True)
        self.down_pushButton.setObjectName("down_pushButton")
        self.right_pushButton = QtWidgets.QPushButton(parent=Button_dialog)
        self.right_pushButton.setGeometry(QtCore.QRect(310, 160, 131, 61))
        self.right_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.right_pushButton.setIcon(icon1)
        self.right_pushButton.setIconSize(QtCore.QSize(85, 60))
        self.right_pushButton.setCheckable(True)
        self.right_pushButton.setAutoExclusive(True)
        self.right_pushButton.setObjectName("right_pushButton")
        self.left_pushButton = QtWidgets.QPushButton(parent=Button_dialog)
        self.left_pushButton.setGeometry(QtCore.QRect(80, 160, 131, 61))
        self.left_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.left_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.left_pushButton.setIcon(icon2)
        self.left_pushButton.setIconSize(QtCore.QSize(90, 65))
        self.left_pushButton.setCheckable(True)
        self.left_pushButton.setAutoExclusive(True)
        self.left_pushButton.setObjectName("left_pushButton")
        self.pushButton_ = QtWidgets.QPushButton(parent=Button_dialog)
        self.pushButton_.setGeometry(QtCore.QRect(230, 20, 61, 121))
        self.pushButton_.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/up.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_.setIcon(icon3)
        self.pushButton_.setIconSize(QtCore.QSize(80, 55))
        self.pushButton_.setCheckable(True)
        self.pushButton_.setAutoExclusive(True)
        self.pushButton_.setObjectName("pushButton_")

        self.retranslateUi(Button_dialog)
        QtCore.QMetaObject.connectSlotsByName(Button_dialog)

    def retranslateUi(self, Button_dialog):
        _translate = QtCore.QCoreApplication.translate
        Button_dialog.setWindowTitle(_translate("Button_dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Button_dialog = QtWidgets.QDialog()
    ui = Ui_Button_dialog()
    ui.setupUi(Button_dialog)
    Button_dialog.show()
    sys.exit(app.exec())
