# Form implementation generated from reading ui file 'my_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon
from Button_dialog import Ui_Button_dialog
from PyQt6.QtGui import QPixmap
import sys


                                                    #########################################################
                                                    ################   HI AQUAPHOTON   ######################
                                                    #########################################################
class Ui_MainWindow(object):
    def openbuttonsWindow(self):         #function to open dialog
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Button_dialog()
        self.ui.setupUi(self.window)
        self.window.show()
    def closebuttonsindow(self):   #function to close dialog
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Button_dialog()
        self.ui.setupUi(self.window)
        self.window.hide()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 34);\n""")


        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ##################################################
        # Aquaphoton logo
        ##################################################

        self.logo_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(700, 50, 250, 200))
        self.logo_label.setText("")
        self.logo_pixmap = QtGui.QPixmap(r"C:\Users\KimoStore\Downloads\FINAL_CONTROL_GUI\aqua\Screenshot 2024-08-13 144740.png")
        self.logo_label.setPixmap(self.logo_pixmap)
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")



        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, -10, 191, 191))
        self.label.setStyleSheet("background-image: url(images/aqua.jfif);\n"
"color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")


        ##################################################
        # label3 and label2 to print current and voltage value
        ##################################################

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 620, 541, 51))
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
";\n"
"font: 75 italic 24pt \"Times New Roman\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.label_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 620, 541, 51))  # Set position and size
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_2.setFont(font)

        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 620, 531, 51))
        self.label_3.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
";\n"
"font: 75 italic 24pt \"Times New Roman\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(600, 690, 521, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 620, 531, 51))  # Set position and size
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_3.setFont(font)

        ##################################################
        #low_pushButton design
        ##################################################

        self.low_pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.low_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 20pt \"Times New Roman\";")
        self.low_pushButton.setCheckable(True)
        self.low_pushButton.setAutoRepeat(False)
        self.low_pushButton.setAutoExclusive(True)
        self.low_pushButton.setFlat(False)
        self.low_pushButton.setObjectName("low_pushButton")
        self.horizontalLayout.addWidget(self.low_pushButton)

        self.low_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.low_pushButton.setGeometry(QtCore.QRect(600, 715, 170, 40))  # Set position and size
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.low_pushButton.setFont(font)

        ##################################################
        #medium_pushButton design
        ##################################################

        self.medium_pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.medium_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 20pt \"Times New Roman\";")
        self.medium_pushButton.setCheckable(True)
        self.medium_pushButton.setAutoRepeat(False)
        self.medium_pushButton.setAutoExclusive(True)
        self.medium_pushButton.setFlat(False)
        self.medium_pushButton.setObjectName("medium_pushButton")
        self.horizontalLayout.addWidget(self.medium_pushButton)

        self.medium_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.medium_pushButton.setGeometry(QtCore.QRect(775, 715, 170, 40))  # Set position and size
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.medium_pushButton.setFont(font)

        self.high_pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.high_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 20pt \"Times New Roman\";")

        ##################################################
        #high_pushButton design
        ##################################################

        self.high_pushButton.setCheckable(True)
        self.high_pushButton.setAutoRepeat(False)
        self.high_pushButton.setAutoExclusive(True)
        self.high_pushButton.setFlat(False)
        self.high_pushButton.setObjectName("high_pushButton")
        self.horizontalLayout.addWidget(self.high_pushButton)

        self.high_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.high_pushButton.setGeometry(QtCore.QRect(951, 715, 170, 40))  # Set position and size
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.high_pushButton.setFont(font)

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 680, 541, 111))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        ##################################################
        # manual_pushButton design
        ##################################################


        self.manual_pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.manual_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 20pt \"Times New Roman\";")
        self.manual_pushButton.setCheckable(True)
        self.manual_pushButton.setChecked(False)
        self.manual_pushButton.setAutoExclusive(True)
        self.manual_pushButton.setAutoDefault(True)
        self.manual_pushButton.setDefault(False)
        self.manual_pushButton.setFlat(False)
        self.manual_pushButton.setObjectName("manual_pushButton")
        self.manual_pushButton.clicked.connect(self.return_car_icon_color)
        self.manual_pushButton.clicked.connect(self.openbuttonsWindow)
        self.horizontalLayout_2.addWidget(self.manual_pushButton)

        self.manual_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.manual_pushButton.setGeometry(QtCore.QRect(10, 715, 270, 40))  # Set position and size
        self.manual_pushButton.setObjectName("low_pushButton")
        self.manual_pushButton.setText("manual")
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.manual_pushButton.setFont(font)

        # auto_pushButton design


        self.auto_pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.auto_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 20pt \"Times New Roman\";")
        self.auto_pushButton.setCheckable(True)
        self.auto_pushButton.setAutoRepeat(False)
        self.auto_pushButton.setAutoExclusive(True)
        self.auto_pushButton.setObjectName("auto_pushButton")
        self.auto_pushButton.clicked.connect(self.change_car_icon_color) 
        self.auto_pushButton.clicked.connect(self.closebuttonsindow) 
        self.horizontalLayout_2.addWidget(self.auto_pushButton)

        self.auto_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.auto_pushButton.setGeometry(QtCore.QRect(283, 715, 270, 40))  # Set position and size
        self.auto_pushButton.setText("Autonomous")
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.auto_pushButton.setFont(font)

       
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(560, 620, 20, 141))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.car_indicator = QtWidgets.QPushButton(parent=self.centralwidget)
        self.car_indicator.setGeometry(QtCore.QRect(210, 540, 121, 71))
        self.car_indicator.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.car_indicator.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/car.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.car_indicator.setIcon(icon)
        self.car_indicator.setIconSize(QtCore.QSize(150, 100))
        self.car_indicator.setFlat(True)
        self.car_indicator.setObjectName("car_indicator")
        self.lowspeed_indicator = QtWidgets.QPushButton(parent=self.centralwidget)
        self.lowspeed_indicator.setGeometry(QtCore.QRect(790, 530, 121, 91))
        self.lowspeed_indicator.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lowspeed_indicator.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/low.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.lowspeed_indicator.setIcon(icon1)
        self.lowspeed_indicator.setIconSize(QtCore.QSize(100, 100))
        self.lowspeed_indicator.setFlat(True)
        self.lowspeed_indicator.setObjectName("lowspeed_indicator")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1166, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "MODE"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Speed"))
        self.low_pushButton.setText(_translate("MainWindow", "Low"))
        self.low_pushButton.clicked.connect(self.low_speed_icon_color) 
        self.medium_pushButton.setText(_translate("MainWindow", "Medium"))
        self.medium_pushButton.clicked.connect(self.medium_speed_icon_color) 
        self.high_pushButton.setText(_translate("MainWindow", "High"))
        self.high_pushButton.clicked.connect(self.high_speed_icon_color) 
        self.manual_pushButton.setText(_translate("MainWindow", "Manual"))
        self.manual_pushButton.clicked.connect(self.change_car_icon_color)
        self.auto_pushButton.setText(_translate("MainWindow", "Autonomous"))
        self.auto_pushButton.clicked.connect(self.return_car_icon_color)

    ##################################################
    #insert of pictures
    ##################################################
    def change_car_icon_color(self):
        # Change the color of the car icon to blue
        blue_pixmap = QPixmap(r"C:\Users\KimoStore\Downloads\FINAL_CONTROL_GUI\aqua\IMG-20240816-WA0008.jpg")
        icon = QIcon(blue_pixmap)
        self.car_indicator.setIcon(icon)

    def return_car_icon_color(self):
        white_pixmap = QPixmap(r"C:\Users\KimoStore\Downloads\FINAL_CONTROL_GUI\aqua\IMG-20240816-WA0007.jpg")
        icon = QIcon(white_pixmap)
        self.car_indicator.setIcon(icon)

    def low_speed_icon_color(self):
        low_pixmap = QPixmap(r"C:\Users\KimoStore\Downloads\FINAL_CONTROL_GUI\aqua\IMG-20240816-WA0012.jpg")
        icon1 = QIcon(low_pixmap)
        self.lowspeed_indicator.setIcon(icon1)  # Change the color of the speed icon to red

    def medium_speed_icon_color(self):
        medium_pixmap = QPixmap(r"C:\Users\KimoStore\Downloads\FINAL_CONTROL_GUI\aqua\IMG-20240816-WA0010.jpg")  # Change the color of the speed icon to yellow
        icon1 = QIcon(medium_pixmap)
        self.lowspeed_indicator.setIcon(icon1)

    def high_speed_icon_color(self):  # Change the color of the speed icon to green
        high_pixmap = QPixmap(r"C:\Users\KimoStore\Downloads\FINAL_CONTROL_GUI\aqua\IMG-20240816-WA0011.jpg")
        icon1 = QIcon(high_pixmap)
        self.lowspeed_indicator.setIcon(icon1)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

                                                    #########################################################
                                                    ################   BYE AQUAPHOTON   #####################
                                                    #########################################################

